name: .NET 9 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore TaskManager_CleanArch_BasicWorkflow.sln

      - name: Build
        run: dotnet build TaskManager_CleanArch_BasicWorkflow.sln --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore TaskManager_CleanArch_BasicWorkflow.sln

      - name: Test
        run: dotnet test TaskManager_CleanArch_BasicWorkflow.sln --no-build --